# site settings

title: Jeremy Schreier
description: Marine microbial ecologist
taglong: PhD, Marine Sciences
tagshort: Jekyll theme
url: https://jschreie.github.io/
baseurl: ""
permalink: pretty
repo: https://github.com/jschreie/jschreie.github.io/

# author settings

author:
  name: Jeremy Schreier
  email: jeremy.e.schreier@gmail.com
photo: /assets/jpg/selfshot.jpg

# social media links

social:
  facebook: username
  github: username
  instagram: username
  linkedin: username
  stackoverflow: 0000000/username
  twitter: username

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
